# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# name: Upload Python Package
name: make_whl3

on:
  workflow_dispatch:
#   release:
#     types: [published]

# permissions:
#   contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [ '3.7', '3.8', '3.9' ]
    # 此处将涉及编译后whl适用的平台
    runs-on: ${{ matrix.os }}
    name: Build ${{ matrix.os }} Python ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version:  ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
#       run: python -m build
      run: python -m build --wheel
    - name: Upload file
      uses: actions/upload-artifact@v3
      with: 
        name: mindnlp-Whl-Python${{ matrix.python-version }}
        path: dist
#     - name: Publish package
#       uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
#       with:
#         user: __token__
#         password: ${{ secrets.PYPI_API_TOKEN }}
